export const CLIENT_LIST_REQUEST = 'CLIENT_LIST_REQUEST';
export const CLIENT_LIST_SUCCESS = 'CLIENT_LIST_SUCCESS';
export const CLIENT_LIST_FAIL = 'CLIENT_LIST_FAIL';

export const CLIENT_REGISTER_REQUEST = 'CLIENT_REGISTER_REQUEST';
export const CLIENT_REGISTER_SUCCESS = 'CLIENT_REGISTER_SUCCESS';
export const CLIENT_REGISTER_FAIL = 'CLIENT_REGISTER_FAIL';
