export const NOTE_REGISTER_REQUEST = 'NOTE_REGISTER_REQUEST';
export const NOTE_REGISTER_SUCCESS = 'NOTE_REGISTER_SUCCESS';
export const NOTE_REGISTER_FAIL = 'NOTE_REGISTER_FAIL';
export const NOTE_LIST_REQUEST = 'NOTE_LIST_REQUEST';
export const NOTE_LIST_SUCCESS = 'NOTE_LIST_SUCCESS';
export const NOTE_LIST_FAIL = 'NOTE_LIST_FAIL';
